-- Browar Pogórza CRM schema. Run once in the Supabase SQL editor (or via load_supabase.py --schema).
-- Single-tenant, single user: every table is readable and writable by any authenticated session,
-- and nothing is exposed to anonymous visitors.

create table if not exists stages (
  code text primary key,
  name text not null,
  semantic text not null check (semantic in ('open', 'won', 'lost')),
  sort integer not null default 0,
  color text not null default '#94a3b8'
);

create table if not exists people (
  id integer primary key,
  name text not null,
  active boolean not null default true
);

create table if not exists companies (
  id integer primary key generated by default as identity,
  name text not null,
  nip text,
  email text,
  phone text,
  address text,
  company_type text,
  comment text,
  owner_id integer references people(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists contacts (
  id integer primary key generated by default as identity,
  first_name text not null,
  last_name text,
  phone text,
  email text,
  position text,
  company_id integer references companies(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id integer primary key generated by default as identity,
  name text not null,
  slug text,
  price numeric(12,2) not null default 0,
  unit text not null default 'szt.',
  active boolean not null default true,
  sort integer not null default 500,
  group_name text,
  image_path text,
  created_at timestamptz not null default now()
);

create table if not exists deals (
  id integer primary key generated by default as identity,
  title text not null,
  company_id integer references companies(id),
  contact_id integer references contacts(id) on delete set null,
  stage_code text not null references stages(code),
  amount numeric(12,2) not null default 0,
  currency text not null default 'PLN',
  begin_date date,
  close_date date,
  closed boolean not null default false,
  repeat_customer boolean not null default false,
  owner_id integer references people(id),
  comment text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  moved_at timestamptz,
  previous_stage_code text
);
create index if not exists deals_stage_idx on deals(stage_code);
create index if not exists deals_company_idx on deals(company_id);

create table if not exists deal_lines (
  id integer primary key generated by default as identity,
  deal_id integer not null references deals(id) on delete cascade,
  product_id integer references products(id),
  product_name text not null,
  price numeric(12,2) not null default 0,
  quantity numeric(12,3) not null default 1,
  discount_rate numeric(6,2) not null default 0,
  discount_sum numeric(12,2) not null default 0,
  sort integer not null default 0
);
create index if not exists deal_lines_deal_idx on deal_lines(deal_id);

create table if not exists stage_history (
  id integer primary key generated by default as identity,
  deal_id integer not null references deals(id) on delete cascade,
  stage_code text not null,
  moved_at timestamptz not null default now(),
  moved_by integer
);
create index if not exists stage_history_deal_idx on stage_history(deal_id);

create table if not exists comments (
  id integer primary key generated by default as identity,
  entity_type text not null check (entity_type in ('deal', 'company', 'contact')),
  entity_id integer not null,
  kind text not null default 'comment' check (kind in ('comment', 'task')),
  author_id integer,
  body text not null,
  deadline timestamptz,
  completed boolean not null default false,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  files jsonb not null default '[]'::jsonb
);
alter table comments add column if not exists pinned boolean not null default false;
create index if not exists comments_entity_idx on comments(entity_type, entity_id);

-- Row level security: authenticated only.
do $$
declare t text;
begin
  foreach t in array array['stages','people','companies','contacts','products','deals','deal_lines','stage_history','comments'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on %I', t);
    execute format('create policy "authenticated full access" on %I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Product photos: public bucket (URLs are unguessable enough for beer bottles), writes for authenticated only.
insert into storage.buckets (id, name, public) values ('products', 'products', true)
on conflict (id) do nothing;
drop policy if exists "products public read" on storage.objects;
create policy "products public read" on storage.objects for select using (bucket_id = 'products');
drop policy if exists "products authenticated write" on storage.objects;
create policy "products authenticated write" on storage.objects for all to authenticated using (bucket_id = 'products') with check (bucket_id = 'products');

-- After bulk-loading rows with explicit ids, bump the identity sequences past the imported maximum.
create or replace function bump_sequences() returns void language plpgsql as $$
declare t text;
begin
  foreach t in array array['companies','contacts','products','deals','deal_lines','stage_history','comments'] loop
    execute format('select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from %I), 0) + 1, false)', t, t);
  end loop;
end $$;
